platform :ios, '8.0'
use_frameworks!

target 'Hydra' do
    pod 'SVProgressHUD',            '~> 1.1'
    pod 'SDWebImage',               '~> 3.7'
    pod 'TUSafariActivity',         :podspec => 'External/TUSafariActivity.podspec'
    pod 'SMPageControl',            '~> 1.2'
    pod 'Reachability',             '~> 3.2'
    pod 'AcknowList'
    pod 'RMPickerViewController',   '~> 2.0.3'
    pod 'CVCalendar',               '~> 1.2.9'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'p2.OAuth2'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'
    pod 'SWXMLHash'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'Bolts'
    pod 'FontAwesome.swift'
end