//
//  FacebookSession.swift
//  Hydra
//
//  Created by Feliciaan De Palmenaer on 03/03/2016.
//  Copyright © 2016 Zeus WPI. All rights reserved.
//

import Foundation
import FBSDKCoreKit
import FBSDKLoginKit
import FBSDKShareKit

// Generated by visiting https://graph.facebook.com/oauth/access_token?client_id=_&client_secret=_&grant_type=client_credentials
let kAppAccessToken = "146947948791011|QqOR99OREkC_vAvOkfJm2tp-02k"
let FacebookSessionStateChangedNotification = "FacebookSessionStateChangedNotification"
let FacebookUserInfoUpdatedNotifcation = "FacebookUserInfoUpdatedNotifcation"

class FacebookSession: NSObject {

    static var sharedSession = FacebookSession()

    override init() {
        super.init()

        self.updateUserInfo()
    }

    var open: Bool {
        if (FBSDKAccessToken.current() != nil) && (userInfo == nil) && !updatingUserInfo {
            self.updateUserInfo(true)
        }
        return FBSDKAccessToken.current() != nil
    }

    var userInfo: FacebookUser?
    var updatingUserInfo = false

    func openWithAllowLoginUI(_ allowLoginUI: Bool, completion: (() -> Void)? = nil) {
        let userLoggedIn = PreferencesService.sharedService.userLoggedInToFacebook
        if !allowLoginUI && !userLoggedIn {
            return
        }
        if self.open {
            self.updateUserInfo()
            return
        }
        let login = FBSDKLoginManager()
        login.logIn(withReadPermissions: ["public_profile", "user_friends"]) { (result, error) -> Void in
            if let error = error {
                // Handle error
                let delegate = UIApplication.shared.delegate as! AppDelegate
                delegate.handleError(error)
            } else {
                if (result?.isCancelled)! || (result?.declinedPermissions.contains("public_profile"))! {
                    // HANDLE DECLINED SHIT
                    PreferencesService.sharedService.userLoggedInToFacebook = false
                } else {
                    // HANDLE WINNING
                    self.updateUserInfo()
                    PreferencesService.sharedService.userLoggedInToFacebook = true
                }
            }

            let center = NotificationCenter.default
            center.post(name: Notification.Name(rawValue: FacebookSessionStateChangedNotification), object: nil)
        }
    }

    func close() {
        let manager = FBSDKLoginManager()
        manager.logOut()
        userInfo = nil
        updatingUserInfo = false
        let center = NotificationCenter.default
        center.post(name: Notification.Name(rawValue: FacebookSessionStateChangedNotification), object: nil)
    }

    fileprivate func updateUserInfo(_ force: Bool = false) {
        if force || self.open { // Use force to not get in a infinite loop
            self.updatingUserInfo = true
            requestWithGraphPath("me", parameters: [:], completionHandler: { (result) -> Void in
                let userName = result.value(forKey: "name") as! String
                let userId = result.value(forKey: "id") as! String

                self.userInfo = FacebookUser(name: userName, id: userId)
                let center = NotificationCenter.default
                center.post(name: Notification.Name(rawValue: FacebookSessionStateChangedNotification), object: nil)
                self.updatingUserInfo = false
            })
        }
    }

    func requestWithQuery(_ query: String, completionHandler: ((AnyObject) -> Void)?) {
        // TODO: change all fql request to open graph request (fix before 7 august 2016)
        self.requestWithGraphPath("/v2.0/fql", parameters: ["q": query], completionHandler: completionHandler)
    }

    func requestWithGraphPath(_ path: String, parameters: [AnyHashable: Any], HTTPMethod: String = "GET", completionHandler: ((AnyObject) -> Void)? ) {
        var parameters = parameters

        if !self.open {
            parameters["access_token"] = kAppAccessToken
        }

        FBSDKGraphRequest(graphPath: path, parameters: parameters, httpMethod: HTTPMethod).start { (connection, obj, err) -> Void in
            if let error = err {
                let app = UIApplication.shared.delegate as! AppDelegate
                app.handleError(error)
                print("An error occured", error) //TODO: add error completion handler
            }
            if let obj = obj {
                if let completionHandler = completionHandler {
                    completionHandler(obj as AnyObject)
                }
            }
        }

    }
}

@objc class FacebookUser: NSObject { // Use class because it's used in Obj-C
    let name: String
    let id: String

    init(name: String, id: String) {
        self.name = name
        self.id = id
    }
}
